server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/blog?characterEncoding=UTF-8&serverTimezone=UTC
    username: kyy
    password: 1111
    
mybatis:
  type-aliases-package: com.kyy.blog.test
  mapper-locations: mappers/**/*.xml